version: 2
jobs:
  build:
    working_directory: ~/game_share
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.6.3-node
         environment:
           RAILS_ENV: test
           PGHOST: 127.0.0.1
           PGUSER: postgres
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
       - image: circleci/postgres:11.5
         environment:
           POSTGRES_USER: postgres
           POSTGRES_DB: game_share_test

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      
      - run:
          name: Install Ruby Dependencies
          command: bundle install

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 120s

      - run:
          name: Database setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate