default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  username: postgres
  password: 

development:
  <<: *default
  database: game_share_development

test:
  <<: *default
  database: game_share_test