default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password:

development:
  <<: *default
  database: game_share_development
  host: <%= ENV['RDS_HOSTNAME'] %>
  username: root
  password: 

test:
  <<: *default
  database: game_share_test